/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    pages: Page;
    posts: Post;
    categories: Category;
    media: Media;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: string;
  name?: string | null;
  roles?: ('admin' | 'user')[] | null;
  photo?: string | Media | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Page {
  id: string;
  title: string;
  richText?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface Post {
  id: string;
  title: string;
  categories?: (string | Category)[] | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  publishedOn?: string | null;
  content: (
    | {
        text?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        media?:
          | {
              media: string | Media;
              size?: ('auto' | 'halfScreen' | 'fullScreen') | null;
              position?: ('left' | 'right' | 'center') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'mediaBlock';
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentBlock';
      }
    | {
        text?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quoteBlock';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
export interface Category {
  id: string;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
